### ISSUE TITLE
go install 安装异常

### ISSUE THREAD

**Issue by cdy1263** [weichangdong/sync-mysql-schema-data#2]
老哥，在安装的时候 go install github.com/weichangdong/sync-mysql-schema-data@latest 会出现这样的错误：
go install: github.com/weichangdong/sync-mysql-schema-data@latest: github.com/weichangdong/sync-mysql-schema-data@v0.0.0-20200702095625-7929d933be57: parsing go.mod:
        module declares its path as: github.com/hidu/mysql-schema-sync
                but was required as: github.com/weichangdong/sync-mysql-schema-data
![image](https://user-images.githubusercontent.com/17767366/132180206-1ddae240-be3b-4dbc-b091-19cbd5807024.png)
请问这样的情况怎么样解决呢（PS，在另外的项目，直接用go install github.com/hidu/mysql-schema-sync@latest是可以正常使用的）
go 语言的新手，希望可以指点一二，多谢。

**Comment by weichangdong** [comment]
先clone下来 然后 执行 go mod tidy

然后 go build main.go  然后执行./main -h 看下OK不?

**Comment by cdy1263** [comment]
不错，可以啦，多谢多谢
